version: 2

sources:
  - name: csv_imports
    database: iceberg_catalog
    schema: default
    tables:
      - name: customers
        description: "CSV files containing customer data"
        external:
          location: s3://warehouse/customers/
          file_format: csv
          options:
            header: true
            delimiter: ','
            nullValue: ''
            dateFormat: 'yyyy-MM-dd'
      
      - name: accounts
        description: "CSV files containing account data"
        external:
          location: s3://warehouse/accounts/
          file_format: csv
          options:
            header: true
            delimiter: ','
            nullValue: ''
            dateFormat: 'yyyy-MM-dd'
      
      - name: branches
        description: "CSV files containing branch data"
        external:
          location: s3://warehouse/branches/
          file_format: csv
          options:
            header: true
            delimiter: ','
            nullValue: ''

      - name: cards
        description: "CSV files containing branch data"
        external:
          location: s3://warehouse/cards/
          file_format: csv
          options:
            header: true
            delimiter: ','
            nullValue: ''
            dateFormat: 'yyyy-MM-dd'

      - name: loans
        description: "CSV files containing loan data"
        external:
          location: s3://warehouse/loans/
          file_format: csv
          options:
            header: true
            delimiter: ','
            nullValue: ''
            dateFormat: 'yyyy-MM-dd'

      - name: merchants
        description: "CSV files containing merchant data"
        external:
          location: s3://warehouse/merchants/
          file_format: csv
          options:
            header: true
            delimiter: ','
            nullValue: ''